steps:
  # Install dependencies and build
  - name: 'node:18-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        npm ci --frozen-lockfile
        npm run build
        ls -la .next/

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/auditor-tool-next:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/auditor-tool-next:latest'
      - '--no-cache'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/auditor-tool-next']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'auditor-tool-next'
      - '--image'
      - 'gcr.io/$PROJECT_ID/auditor-tool-next:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'NODE_ENV=production'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

timeout: '1800s'  # 30 minutes

images:
  - 'gcr.io/$PROJECT_ID/auditor-tool-next:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/auditor-tool-next:latest'