steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/auditor-tool-next:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/auditor-tool-next:latest'
      - '.'

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/auditor-tool-next']

  # Deploy to Cloud Run (will use your existing env vars)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'auditor-tool-next'
      - '--image'
      - 'gcr.io/$PROJECT_ID/auditor-tool-next:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '2Gi'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'

images:
  - 'gcr.io/$PROJECT_ID/auditor-tool-next:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/auditor-tool-next:latest'